apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: client-rule
spec:
  host: client-srv.postsapp.svc.cluster.local
  subsets:
  - name: client-v1
    labels:
      version: v1.0
  - name: client-v2
    labels:
      version: v2.0
  - name: client-v3
    labels:
      version: v3.0