apiVersion: v1
kind: Secret
metadata:
  namespace: tubes-kpk
  name: stg-mongo-member-secret
type: Opaque
data:
  user: bWVtYmVyZGI= #memberdb
  password: bmF0aGFuMTIz #nathan123
  internal_auth: MGNIRUI3YVNiM1FkNk1RWnpOWjFYMGw3bzdCSXliM1I= #0cHEB7aSb3Qd6MQZzNZ1X0l7o7BIyb3R