apiVersion: v1
kind: Secret
metadata:
  namespace: tubes-kpk
  name: stg-analytics-secret
type: Opaque
data:
  secret: dGhpc2lzYXNlY3JldA== #thisisasecret
  internal_auth: MGNIRUI3YVNiM1FkNk1RWnpOWjFYMGw3bzdCSXliM1I= #0cHEB7aSb3Qd6MQZzNZ1X0l7o7BIyb3R