apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443 
      name: https
      protocol: HTTPs
    tls: 
      mode: SIMPLE
      credentialName: launathiel-domain-cert-prod
    hosts:
    - "posts.launathiel.com"